### PR TITLE
Added tags to GameObjects.

### PR DESCRIPTION
**Pull request by bradcooper314**
I used a list to ensure tags are unique and it was simple enough to do in the header alone.

I don't believe there's a need for any asserts or error checking for something as simple as tags.

### CODE REVIEW

**Comment by MatthewWhite** [comment]
+1

**Comment by MatthewWhite** [comment]
Once this and #3 are merged, we should add the ability to parse the tags from the xml as part of loading a `GameObject`.  I've added it to the backlog, but figured I would also put it here for visibility.

**Comment by bradcooper314** [comment]
Not necessarily. I envisioned Components as being the ones to manage the tags of their parent GameObject, not that it's inherently attached to the GameObject itself. As to how each Component knows what tag to add/remove/manage, that could be hardcoded into the component or put into the XML for that component if we want.
if we want.

**Comment by MatthewWhite** [comment]
I would avoid hardcoding for the simple fact that it's easy to data drive, so why not data drive it? As for on component versus on game object, I think game object makes more sense.  If it's based on components, then what advantage does this give over just querying whether the game object has that particular component?

**Review by MatthewWhite — APPROVED** [review]

**Pull request merged**
